# starts with --- (three hyphens)
# yml very sensitive to indentation - be careful and double check
---

# name the play
- name: install mongodb
  # where we want to install or run this play
  hosts: db

  # do we want comprehensive facts from the host?
  gather_facts: true

  # do we want/need admin access here (sudo)?
  become: true

  # instructions/actions known as tasks put here. Playbook consists of plays. Inside of each play, can have multiple tasks.
  tasks:
  - name: update apt cache
    ansible.builtin.apt:
      update_cache: yes
  
  - name: upgrade all packages
    ansible.builtin.apt:
      upgrade: dist # dist stands for distributions

  - name: Add GPG key
    become: true
    ansible.builtin.apt_key:
      url: https://www.mongodb.org/static/pgp/server-7.0.asc
      state: present
 
  - name: Add the MongoDB repository
    ansible.builtin.apt_repository:
      repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
      state: present
      update_cache: yes
 
  - name: Install MongoDB 7.0
    ansible.builtin.apt:
      name: mongodb-org=7.0.6
      state: present